version: '3.8'
services:
  movies:
    image: ansaricloud/moviesrepo:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: ansaricloud/trainrepo:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  recharge:
    image: ansaricloud/rechargerepo:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  dth:
    image: ansaricloud/dthrepo:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
